### PR TITLE
ARCore preview 2 ( #15 )

### PR DESCRIPTION
**Pull request by iBicha**
I created this pull request mainly to integrate ARCore preview 2, but also to discuss interface in #15 

`StartService` is now an `IEnumerator` in the `ARInterface` that can be started as a coroutine, and returns only when done (waiting for camera, user permission, etc). All classes implementing the interface has been updated as well.

Added a `IsRunning` property to `ARInterface` to be able to tell if the starting of the interface was successful. `serviceRunning` is not properly updated in case of an interruption, so for now it is mainly used right after `StartService` returns. `ARController`and `ARRemoteDevice` are updated accordingly, and this means that this update will not break ARInterface projects, and the transition should be seemless.

Added a `IsSupported` preperty which calls `IsARKitSessionConfigurationSupported()` on ARKit and `SessionManager.CheckSupported()` on ARCore. defaults to true for other implementations.

`ARCoreInterface` has been updated to work with ARCore preview 2 for getting cloud points, planes, light estimation and proper camera setup.

`TryGetCameraImage` see [here](https://github.com/Unity-Technologies/experimental-ARInterface/pull/17#issuecomment-353149121)

### CODE REVIEW

**Comment by iBicha** [comment]
For `TryGetCameraImage` see [here](https://github.com/Unity-Technologies/experimental-ARInterface/pull/18#issuecomment-352869282)

**Comment by iBicha** [comment]
Eventually implemented `TryGetCameraImage` using the native TextureReader utility used in the computer vision example, and the performance is not terrible.

Note that the first call to `TryGetCameraImage` will return false. the next call will return the image from the last time you called `TryGetCameraImage`. It is to best to call this method every frame, or at least call it twice in to consecutive frames to get a 1 frame old image.

**Comment by Crashthatch** [comment]
I've switched from #18 to #17 because it seems more fully-featured (I can wait for startup externally, and can use .isSupported & tryGetCameraImage), so vote for this one being merged despite the API changes, then the fixes from PR #18 can be remade on top of this branch.

@iBicha TryGetCameraImage works - I think it is giving me back slightly different dimensions (view is stretched differently?) than in arcore-preview-1, but I can cope with that (they seemed arbitrary before anyway). However, when I call TryGetCameraImage it seems to break an unrelated conversion from a RenderTexture to Texture2D coming from a simulated camera:

My code runs every 30 frames in a coroutine like:
```
ARInterface.GetInterface().TryGetCameraImage(ref realImage);
yield return null; //Must wait until next frame then call tryGetCameraImage again to get the result from this frame (https://github.com/Unity-Technologies/experimental-ARInterface/pull/17#issuecomment-353149121).
if( ARInterface.GetInterface().TryGetCameraImage(ref realImage) ){
//TODO- Do something with the image. Nothing yet.
}

RenderTexture.active = (RenderTexture)renderTexture;
simulatedCameraTexture2D.ReadPixels(new UnityEngine.Rect(0f, 0f, simulatedWidth, simulatedHeight), 0, 0, false);
simulatedCameraTexture2D.Apply(false, false);

//Output for debug
_debugCube.GetComponent<Renderer>().material.mainTexture = simulatedCameraTexture2D;
```

But the output texture looks usually black, sometimes with distorted versions of textures used within the application (see cube in center of screenshot)- I'd guess it's outputting some random chunk of memory instead of the correct values? Outputting the renderTexture (instead of simulatedCameraTexture2D) on the last line looks as I would expect. Commenting out the `ARInterface.GetInterface().TryGetCameraImage` lines means it works as it used to again.

I'll continue debugging tomorrow, but do you have any ideas for what might be causing / how to fix? Could the C part of  TryGetCameraImage somehow be using the same memory or something and interfering with the texture-to-texture2d code that happens afterwards?

screenshot_20171222-172354

**Comment by iBicha** [comment]
I have a couple of pointers, waiting for next frame should be done with [WaitForEndOfFrame](https://docs.unity3d.com/ScriptReference/WaitForEndOfFrame.html) 

I'm investigating this as well, but I think this is due to an issue I mention here google-ar/arcore-unity-sdk/issues/66. folks at Google are aware of this and will probably fix it in the next update.

Also note that `TryGetCameraImage` makes a call to [GL.InvalidateState()](https://docs.unity3d.com/ScriptReference/GL.InvalidateState.html) which "invalidates the render state", and it was a work around the issue mentioned in the first place. 

To dig deeper, from [glBindBuffer](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glBindBuffer.xhtml) it says that calling it with `GL_PIXEL_PACK_BUFFER` affects `glReadPixels`. I'm no GL expert, but I think this is exactly what's going on.

Overall, since both Unity and Google are working on their interfaces, and both are experimental/in preview, try finding a temporary hack to get by until the actual stuff is out. Did you try doing the simulated camera thing before calling `TryGetCameraImage`? Might fix it

**Comment by jimmy-jam** [comment]
I've merged pr #18 to master - could you redo your improvements based on that?

**Comment by iBicha** [comment]
Sure, since this PR is no longer relevant (it's not about ARCore Preview 2 anymore) I'll close it and create add the improvements separately for the sake of clarity

**Comment by jimmy-jam** [comment]
Thank you so much!

**Pull request closed without merging**
